name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Installing
      run: yarn install --frozen-lockfile
    - name: Linting
      run: yarn lint
    - name: UnitTesting
      run: yarn test
    - name: Building
      run: yarn build
    - name: Anti-tamper check
      run: git diff --exit-code